
// testing for elastic API
###
GET http://localhost:9200 HTTP/1.1

###
GET http://localhost:9200/esql HTTP/1.1
###
GET http://localhost:9200/myindex/_mapping?pretty HTTP/1.1

###
DELETE http://localhost:9200/esql HTTP/1.1

###
PUT http://localhost:9200/esql HTTP/1.1

###
PUT http://localhost:9200/esql HTTP/1.1
content-type: application/json

{
    "mappings": {
        "user": {
            "properties": {
                "name": {
                    "type": "text"
                },
                "user_name": {
                    "type": "keyword"
                },
                "email": {
                    "type": "keyword"
                }
            }
        }
    }
}
#####

GET http://localhost:9200/_cat/indices?v HTTP/1.1

####
PUT http://localhost:9200/myindex/_mapping/_doc HTTP/1.1
content-type: application/json

{"properties":{"Age":{"type":"integer"},"As3":{"properties":{"Name":{"type":"keyword"}},"type":"nested"},"Gender":{"enable":false},"Golang":{"dynamic":"strict","enable":"false","properties":{"Last":{"type":"text"}}},"JoinDate":{"ignore_above":"500","type":"date"},"Mysql":{"type":"object"}}}
####

POST http://localhost:9200/myindex/_search?size=0 HTTP/1.1
content-type: application/json

{
    "aggs" : {
        "avg_grade" : {
            "avg" : { 
                "field" : "Age"
            } 
        },
        "avg_age" : {
            "avg" : { 
                "field" : "Ages"
            } 
        }
    }
}

